import { useState } from 'react';
import { Ionicons } from '@expo/vector-icons';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { Card, ConfirmDialog, PrimaryButton, TopBar } from '@/src/components/ui';
import { Routine } from '@/src/domain/types';
import { useAppStore } from '@/src/store/AppStore';
import { colors, days, shortDays } from '@/src/theme';

export function RoutinesScreen({ onCreate, onRoutine }: { onCreate(): void; onRoutine(routine: Routine): void }) {
  const { routines } = useAppStore();
  return <View style={styles.fill}><TopBar title="Mis Rutinas" action={<Pressable accessibilityRole="button" accessibilityLabel="Crear rutina" onPress={onCreate} style={styles.plus}><Ionicons name="add" color={colors.text} size={22} /></Pressable>} /><ScrollView contentContainerStyle={styles.content}>{routines.map(routine => <Pressable accessibilityRole="button" accessibilityLabel={`Abrir rutina ${routine.name}`} key={routine.id} onPress={() => onRoutine(routine)} style={styles.routineCard}><View style={styles.dayBox}><Text style={styles.day}>{shortDays[routine.day - 1]}</Text><Ionicons name="barbell-outline" color={colors.dim} size={16} /></View><View style={styles.grow}><Text style={styles.strong}>{routine.name}</Text><Text style={styles.dim}>{routine.exercises.length} ejercicios · {routine.exercises.reduce((sum, item) => sum + item.sets.length, 0)} series</Text></View><Ionicons name="chevron-forward" color={colors.subtle} size={16} /></Pressable>)}{routines.length === 0 && <Card><Text style={styles.muted}>Aún no tienes rutinas.</Text><PrimaryButton title="Crear primera rutina" onPress={onCreate} /></Card>}</ScrollView></View>;
}

export function CreateRoutineScreen({ onBack, onSaved }: { onBack(): void; onSaved(routine: Routine): void }) {
  const { exercises, routines, createRoutine } = useAppStore(); const [name, setName] = useState(''); const [day, setDay] = useState(1); const [selected, setSelected] = useState<string[]>([]); const atLimit = routines.length >= 7; const disabled = !name.trim() || !selected.length || atLimit;
  const save = () => { if (disabled) return; onSaved(createRoutine({ name, day, exerciseIds: selected })); };
  return <View style={styles.fill}><TopBar title="Nueva rutina" onBack={onBack} action={<Pressable accessibilityRole="button" accessibilityLabel="Guardar rutina" disabled={disabled} onPress={save}><Text style={[styles.save, disabled && styles.disabled]}>Guardar</Text></Pressable>} /><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={styles.content}><Text style={styles.label}>NOMBRE</Text><TextInput value={name} onChangeText={setName} placeholder="Ej. Día A · Sentadilla" placeholderTextColor={colors.subtle} style={styles.input} /><Text style={styles.label}>DÍA</Text><View style={styles.chips}>{days.map((label, index) => <Pressable accessibilityRole="button" accessibilityLabel={label} key={label} onPress={() => setDay(index + 1)} style={[styles.chip, day === index + 1 && styles.chipActive]}><Text style={[styles.chipText, day === index + 1 && styles.chipTextActive]}>{label.slice(0,3)}</Text></Pressable>)}</View><Text style={styles.label}>EJERCICIOS</Text>{exercises.map(exercise => { const active = selected.includes(exercise.id); return <Pressable accessibilityRole="checkbox" accessibilityLabel={exercise.name} accessibilityState={{ checked: active }} key={exercise.id} onPress={() => setSelected(current => active ? current.filter(id => id !== exercise.id) : [...current, exercise.id])} style={[styles.exerciseRow, active && styles.exerciseActive]}><View><Text style={styles.strong}>{exercise.name}</Text><Text style={styles.dim}>{exercise.muscle}</Text></View><Ionicons name={active ? 'checkmark' : 'add'} color={active ? colors.orange : colors.dim} size={18} /></Pressable>; })}{atLimit && <Text style={styles.warning}>Ya tienes el máximo de 7 rutinas activas. Elimina una para crear otra.</Text>}</ScrollView></View>;
}

export function RoutineDetailScreen({ routine, onBack, onStart, onDeleted }: { routine: Routine; onBack(): void; onStart(): void; onDeleted(): void }) {
  const { duplicateRoutine, deleteRoutine } = useAppStore(); const [confirmDelete, setConfirmDelete] = useState(false);
  const remove = () => { deleteRoutine(routine.id); setConfirmDelete(false); onDeleted(); };
  return <View style={styles.fill}><TopBar title={routine.name} eyebrow={days[routine.day - 1].toUpperCase()} onBack={onBack} action={<Pressable accessibilityRole="button" accessibilityLabel="Duplicar rutina" onPress={() => duplicateRoutine(routine.id)}><Text style={styles.muted}>Duplicar</Text></Pressable>} /><View style={styles.cta}><PrimaryButton title="Iniciar entrenamiento" onPress={onStart} /></View><ScrollView contentContainerStyle={styles.content}>{routine.exercises.map(exercise => <View key={exercise.id} style={styles.exerciseBlock}><View style={styles.rowBetween}><Text style={styles.strong}>{exercise.name}</Text><Text style={styles.dim}>{exercise.muscle}</Text></View><Card><View style={styles.tableHead}><Text style={styles.setNo}>SET</Text><Text style={styles.col}>PESO</Text><Text style={styles.col}>REPS</Text><Text style={styles.col}>RPE</Text></View>{exercise.sets.map((set, index) => <View key={set.id} style={styles.tableRow}><Text style={[styles.setNo, set.type === 'warmup' && styles.warmup]}>{set.type === 'warmup' ? 'W' : exercise.sets.slice(0, index + 1).filter(item => item.type === 'working').length}</Text><Text style={styles.colValue}>{set.weight}kg</Text><Text style={styles.colValue}>{set.reps}</Text><Text style={styles.colValue}>{set.rpe ? `@${set.rpe}` : '—'}</Text></View>)}</Card></View>)}<Pressable accessibilityRole="button" accessibilityLabel="Eliminar rutina" onPress={() => setConfirmDelete(true)} style={styles.delete}><Text style={styles.deleteText}>Eliminar rutina</Text></Pressable></ScrollView><ConfirmDialog visible={confirmDelete} title="Eliminar rutina" message={`¿Eliminar “${routine.name}”? Esta acción no se puede deshacer.`} confirmLabel="Eliminar" destructive onCancel={() => setConfirmDelete(false)} onConfirm={remove} /></View>;
}

const styles = StyleSheet.create({ fill:{flex:1},grow:{flex:1},content:{padding:20,gap:12,paddingBottom:40},plus:{backgroundColor:colors.orange,width:38,height:38,borderRadius:12,alignItems:'center',justifyContent:'center'},routineCard:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:14,padding:14,flexDirection:'row',alignItems:'center',gap:14},dayBox:{width:50,height:50,borderRadius:12,backgroundColor:colors.elevated,alignItems:'center',justifyContent:'center',gap:4},day:{color:colors.orange,fontSize:10,fontWeight:'700'},strong:{color:colors.text,fontWeight:'700'},dim:{color:colors.dim,fontSize:12,marginTop:3},muted:{color:colors.muted},label:{color:colors.dim,fontSize:10,fontWeight:'700',letterSpacing:1.5,marginTop:8},input:{backgroundColor:colors.surface,borderColor:colors.border,borderWidth:1,borderRadius:12,padding:15,color:colors.text,fontSize:15},chips:{flexDirection:'row',flexWrap:'wrap',gap:7},chip:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:9,paddingHorizontal:12,paddingVertical:9},chipActive:{backgroundColor:colors.orange,borderColor:colors.orange},chipText:{color:colors.muted,fontSize:11,fontWeight:'700'},chipTextActive:{color:colors.text},exerciseRow:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:12,padding:14,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},exerciseActive:{borderColor:'#683017'},save:{color:colors.orange,fontWeight:'700'},disabled:{color:colors.subtle},warning:{color:colors.warning,fontSize:12},cta:{paddingHorizontal:20,paddingBottom:8},exerciseBlock:{gap:8},rowBetween:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},tableHead:{flexDirection:'row',paddingBottom:6,borderBottomWidth:1,borderBottomColor:colors.border},tableRow:{flexDirection:'row',paddingVertical:7},setNo:{width:42,color:colors.dim,fontFamily:'monospace',fontSize:11},col:{flex:1,color:colors.dim,fontFamily:'monospace',fontSize:11},colValue:{flex:1,color:colors.text,fontFamily:'monospace',fontSize:13},warmup:{color:colors.warning},delete:{padding:16,alignItems:'center'},deleteText:{color:colors.danger,fontSize:13},
});
