import { PropsWithChildren, ReactNode } from 'react';
import { Ionicons } from '@expo/vector-icons';
import { Modal, Platform, Pressable, SafeAreaView, ScrollView, StyleProp, StyleSheet, Text, View, ViewStyle } from 'react-native';
import { Tab } from '@/src/domain/types';
import { colors, condensed } from '@/src/theme';

export function Brand({ compact = false }: { compact?: boolean }) { return <View><Text style={styles.kicker}>POWERLIFTING TRACKER</Text><Text style={[styles.brand, compact && styles.brandCompact]}>PWRLFTNG</Text></View>; }
export function Card({ children, style }: PropsWithChildren<{ style?: StyleProp<ViewStyle> }>) { return <View style={[styles.card, style]}>{children}</View>; }
export function PrimaryButton({ title, onPress, light, disabled }: { title: string; onPress(): void; light?: boolean; disabled?: boolean }) { return <Pressable accessibilityRole="button" accessibilityLabel={title} disabled={disabled} onPress={onPress} style={({ pressed }) => [styles.primary, light && styles.primaryLight, disabled && styles.disabled, pressed && styles.pressed]}><Text style={[styles.primaryText, light && styles.primaryTextLight]}>{title}</Text></Pressable>; }
export function TopBar({ title, eyebrow, onBack, action }: { title: string; eyebrow?: string; onBack?(): void; action?: ReactNode }) { return <View style={styles.topBar}>{onBack && <Pressable accessibilityRole="button" accessibilityLabel="Volver" onPress={onBack} hitSlop={12}><Ionicons name="chevron-back" color={colors.muted} size={24} /></Pressable>}<View style={styles.topTitle}>{eyebrow && <Text style={styles.orangeLabel}>{eyebrow}</Text>}<Text style={styles.title}>{title}</Text></View>{action ?? <View />}</View>; }
export function Page({ children, scroll = true }: PropsWithChildren<{ scroll?: boolean }>) { return <SafeAreaView style={styles.page}>{scroll ? <ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={styles.content}>{children}</ScrollView> : children}</SafeAreaView>; }
export function BottomNav({ tab, onTab }: { tab: Tab; onTab(tab: Tab): void }) { const tabs: [Tab, keyof typeof Ionicons.glyphMap, string][] = [['home','home-outline','Inicio'],['workout','barbell-outline','Entreno'],['profile','person-outline','Perfil']]; return <View style={styles.nav}>{tabs.map(([key, icon, label]) => <Pressable accessibilityRole="button" accessibilityLabel={label} accessibilityState={{ selected: tab === key }} key={key} onPress={() => onTab(key)} style={styles.navItem}><Ionicons name={icon} color={tab === key ? colors.text : colors.subtle} size={21} /><Text style={[styles.navText, tab === key && styles.navTextActive]}>{label.toUpperCase()}</Text></Pressable>)}</View>; }
export function AppShell({ children, tab, onTab, showNav = true }: PropsWithChildren<{ tab: Tab; onTab(tab: Tab): void; showNav?: boolean }>) { return <SafeAreaView style={styles.page}><View style={styles.shellBody}>{children}</View>{showNav && <BottomNav tab={tab} onTab={onTab} />}</SafeAreaView>; }
export function ConfirmDialog({ visible, title, message, confirmLabel, destructive = false, onCancel, onConfirm }: { visible: boolean; title: string; message: string; confirmLabel: string; destructive?: boolean; onCancel(): void; onConfirm(): void }) {
  return <Modal visible={visible} transparent animationType="fade" onRequestClose={onCancel}><View style={styles.modalBackdrop}><Pressable accessibilityRole="button" accessibilityLabel="Cerrar diálogo" onPress={onCancel} style={StyleSheet.absoluteFill} /><View accessibilityRole="alert" style={styles.dialog}><Text style={styles.dialogTitle}>{title}</Text><Text style={styles.dialogMessage}>{message}</Text><View style={styles.dialogActions}><Pressable accessibilityRole="button" accessibilityLabel="Cancelar" onPress={onCancel} style={styles.dialogSecondary}><Text style={styles.dialogSecondaryText}>Cancelar</Text></Pressable><Pressable accessibilityRole="button" accessibilityLabel={confirmLabel} onPress={onConfirm} style={[styles.dialogConfirm, destructive && styles.dialogDestructive]}><Text style={styles.dialogConfirmText}>{confirmLabel}</Text></Pressable></View></View></View></Modal>;
}
export const formatTime = (seconds: number) => `${Math.floor(seconds / 60).toString().padStart(2, '0')}:${(seconds % 60).toString().padStart(2, '0')}`;
export const formatDate = (value: string) => new Date(value).toLocaleDateString('es-CL', { day: 'numeric', month: 'short' });

const styles = StyleSheet.create({
  page:{flex:1,backgroundColor:colors.background},shellBody:{flex:1},content:{padding:20,paddingTop:12,gap:14,paddingBottom:30},
  kicker:{color:colors.orange,fontSize:10,fontWeight:'700',letterSpacing:3},brand:{color:colors.text,fontSize:48,fontWeight:'900',fontFamily:condensed,letterSpacing:-1},brandCompact:{fontSize:28},
  card:{backgroundColor:colors.surface,borderRadius:16,borderWidth:1,borderColor:colors.border,padding:16,gap:12},
  primary:{backgroundColor:colors.orange,borderRadius:12,paddingVertical:15,paddingHorizontal:16,alignItems:'center',justifyContent:'center',marginTop:4},primaryLight:{backgroundColor:colors.text},primaryText:{color:colors.text,fontWeight:'800',fontSize:14},primaryTextLight:{color:colors.background},disabled:{opacity:.35},pressed:{opacity:.75},
  topBar:{paddingHorizontal:20,paddingVertical:16,flexDirection:'row',alignItems:'center',gap:12,borderBottomColor:colors.border,borderBottomWidth:StyleSheet.hairlineWidth},topTitle:{flex:1},title:{color:colors.text,fontSize:25,fontWeight:'900',fontFamily:condensed},orangeLabel:{color:colors.orange,fontSize:10,fontWeight:'700',letterSpacing:1.5},
  nav:{height:Platform.OS === 'ios' ? 76 : 68,borderTopWidth:1,borderTopColor:'#1a1a1a',flexDirection:'row',backgroundColor:colors.background},navItem:{flex:1,alignItems:'center',justifyContent:'center',gap:4},navText:{color:colors.subtle,fontSize:9,fontWeight:'700',letterSpacing:1},navTextActive:{color:colors.text},
  modalBackdrop:{flex:1,backgroundColor:'rgba(0,0,0,.76)',justifyContent:'flex-end',padding:18},dialog:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:18,padding:20,gap:12},dialogTitle:{color:colors.text,fontSize:23,fontWeight:'900',fontFamily:condensed},dialogMessage:{color:colors.muted,fontSize:14,lineHeight:20},dialogActions:{flexDirection:'row',gap:10,marginTop:8},dialogSecondary:{flex:1,borderWidth:1,borderColor:colors.border,borderRadius:11,paddingVertical:13,alignItems:'center'},dialogSecondaryText:{color:colors.muted,fontWeight:'700'},dialogConfirm:{flex:1,backgroundColor:colors.orange,borderRadius:11,paddingVertical:13,alignItems:'center'},dialogDestructive:{backgroundColor:colors.danger},dialogConfirmText:{color:colors.text,fontWeight:'800'},
});
